print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? $"))
tip_amount = int(input("How much tip would you like to give? 10, 12, or 15?"))
no_of_people = int(input("How many people to split the bill?"))
individuals_amount = print("Each person should pay: $",(total_bill + tip_amount)/ no_of_people)
